FROM nginx AS runtime-image
WORKDIR /app

COPY dist /app/dist
COPY docker-entrypoint.sh /opt/docker-entrypoint.sh
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf.static /etc/nginx/conf.d/default.conf.template
EXPOSE 8000 8000
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
