export const SETTINGS_PER_MODULE = {
  DOMAIN: ['CREDENTIALS', 'DARK_WEB', 'DOMAIN_PROTECTION', 'MALWARE', 'HACKTIVISM', 'DATA_LEAKAGE'],
  IP: ['CREDENTIALS', 'MALWARE', 'HACKTIVISM', 'DARK_WEB'],
  EMAIL: ['CREDENTIALS'],
  KEYWORD: [
    'DATA_LEAKAGE',
    'DOMAIN_PROTECTION',
    'HACKTIVISM',
    'MEDIA_TRACKER',
    'DARK_WEB',
    'MOBILE_APPS',
    'SOCIAL_MEDIA'
  ],
  FILENAME: ['DATA_LEAKAGE'],
  CONFIDENTIAL: ['DATA_LEAKAGE'],
  FILE_EXTENSION: ['DATA_LEAKAGE'],
  TYPOSQUATTING: ['DOMAIN_PROTECTION'],
  TYPO_KEYWORD_REGEX: ['DOMAIN_PROTECTION'],
  TYPO_KEYWORD_DISTANCE: ['DOMAIN_PROTECTION'],
  BANK: ['CREDIT_CARDS_FULL'],
  CREDIT_CARD: ['CREDIT_CARDS_FULL'],
  CPE_TECH: ['HACKTIVISM'],
  RSS: ['HACKTIVISM', 'MEDIA_TRACKER'],
  TWITTER_PROFILE: ['HACKTIVISM'],
  EXTRA_CATEGORIES: ['MEDIA_TRACKER'],
  IMAGE: ['SOCIAL_MEDIA'],
  TWEETS_FROM_PROFILE: ['MEDIA_TRACKER']
};

export const MODULES_TYPES_DICTIONARY = {
  CUSTOM: 'Custom',
  DOMAIN_PROTECTION: 'Domain Protection',
  CREDIT_CARDS_FULL: 'Credit Cards',
  MOBILE_APPS: 'Mobile Apps',
  MALWARE: 'Malware',
  CREDENTIALS: 'Credentials',
  DATA_LEAKAGE: 'Data Leakage',
  SOCIAL_MEDIA: 'Social Media',
  HACKTIVISM: 'Hacktivism',
  MEDIA_TRACKER: 'Media Tracker',
  DARK_WEB: 'Dark Web',
  THREAT_CONTEXT: 'Threat Context'
};
